"""
Apache Configuration Generator - PHP-FPM Automation Agent
============================================================
Generates production-grade Apache vhost configs with
event MPM, proxy_fcgi, and PHP-FPM integration.
"""

import os
import re
import subprocess
from typing import Dict, Tuple

from modules.logger import DeployLogger
from modules.system import SystemDetector
from modules.backup import BackupManager


class ApacheConfigurator:
    """
    Generates and manages Apache VirtualHost configurations:
    - Event MPM with proxy_fcgi (modern, performant)
    - Per-service vhost files
    - PHP-FPM socket integration via proxy
    - Security hardening
    - SSL/TLS support
    - Safe config testing before reload
    """

    VHOST_HTTP_TEMPLATE = """# ============================================================
# Apache VirtualHost: {service_name}
# Domain:  {domain}
# PHP:     {php_version} via FPM (proxy_fcgi)
# Socket:  {fpm_socket}
# Generated by PHP-FPM Automation Agent
# ============================================================

<VirtualHost *:80>
    ServerName {domain}
{server_alias_line}
    ServerAdmin webmaster@{domain}

    DocumentRoot {document_root}

    # Logging
    ErrorLog  ${{APACHE_LOG_DIR}}/{service_name}-error.log
    CustomLog ${{APACHE_LOG_DIR}}/{service_name}-access.log combined

    # ── PHP-FPM via proxy_fcgi ──────────────────────────────
    <FilesMatch "\\.php$">
        SetHandler "proxy:unix:{fpm_socket}|fcgi://localhost"
    </FilesMatch>

    # ── Document Root Permissions ───────────────────────────
    <Directory {document_root}>
        Options -Indexes +FollowSymLinks -MultiViews
        AllowOverride All
        Require all granted

        # Enable PATH_INFO for MVC frameworks (e.g., /index.php/controller/action)
        AcceptPathInfo On

        # URL rewriting (like mod_rewrite for Laravel/WP)
        <IfModule mod_rewrite.c>
            RewriteEngine On
            RewriteCond %{{REQUEST_FILENAME}} !-d
            RewriteCond %{{REQUEST_FILENAME}} !-f
            RewriteRule ^ index.php [L]
        </IfModule>
    </Directory>

    # ── Security Headers ────────────────────────────────────
    <IfModule mod_headers.c>
        Header always set X-Frame-Options "SAMEORIGIN"
        Header always set X-Content-Type-Options "nosniff"
        Header always set X-XSS-Protection "1; mode=block"
        Header always set Referrer-Policy "strict-origin-when-cross-origin"
        Header always set Permissions-Policy "camera=(), microphone=(), geolocation=()"

        # Remove server signature
        Header always unset X-Powered-By
        Header always unset Server
    </IfModule>

    # ── Deny Hidden Files ───────────────────────────────────
    <DirectoryMatch "/\\.">
        Require all denied
    </DirectoryMatch>

    # ── Deny Sensitive Files ────────────────────────────────
    <FilesMatch "^\\.(env|git|htaccess|htpasswd)">
        Require all denied
    </FilesMatch>

    <FilesMatch "(composer\\.json|composer\\.lock|package\\.json|package-lock\\.json)$">
        Require all denied
    </FilesMatch>

    # ── Deny PHP in Uploads ─────────────────────────────────
    <DirectoryMatch "/(?:uploads|files)/">
        <FilesMatch "\\.php$">
            Require all denied
        </FilesMatch>
    </DirectoryMatch>

    # ── Static Asset Caching ────────────────────────────────
    <IfModule mod_expires.c>
        ExpiresActive On
        ExpiresByType text/css "access plus 1 month"
        ExpiresByType text/javascript "access plus 1 month"
        ExpiresByType application/javascript "access plus 1 month"
        ExpiresByType image/png "access plus 1 month"
        ExpiresByType image/jpeg "access plus 1 month"
        ExpiresByType image/gif "access plus 1 month"
        ExpiresByType image/svg+xml "access plus 1 month"
        ExpiresByType font/woff2 "access plus 1 month"
    </IfModule>

    # ── Gzip Compression ────────────────────────────────────
    <IfModule mod_deflate.c>
        AddOutputFilterByType DEFLATE text/plain
        AddOutputFilterByType DEFLATE text/css
        AddOutputFilterByType DEFLATE text/javascript
        AddOutputFilterByType DEFLATE text/xml
        AddOutputFilterByType DEFLATE application/json
        AddOutputFilterByType DEFLATE application/javascript
        AddOutputFilterByType DEFLATE application/xml
        AddOutputFilterByType DEFLATE image/svg+xml
        AddOutputFilterByType DEFLATE font/opentype
    </IfModule>

    # ── Upload Size Limit ───────────────────────────────────
    LimitRequestBody {max_upload_bytes}

{extra_config}
</VirtualHost>
"""

    VHOST_SSL_REDIRECT = """# HTTP → HTTPS redirect for {domain}
<VirtualHost *:80>
    ServerName {domain}
    ServerAlias www.{domain}

    RewriteEngine On
    RewriteCond %{{HTTPS}} off
    RewriteRule ^(.*)$ https://%{{HTTP_HOST}}%{{REQUEST_URI}} [R=301,L]
</VirtualHost>
"""

    VHOST_SSL_TEMPLATE = """# ============================================================
# Apache SSL VirtualHost: {service_name}
# Domain:  {domain}
# PHP:     {php_version} via FPM (proxy_fcgi)
# Socket:  {fpm_socket}
# Generated by PHP-FPM Automation Agent
# ============================================================

<VirtualHost *:443>
    ServerName {domain}
{server_alias_line}
    ServerAdmin webmaster@{domain}

    DocumentRoot {document_root}

    # SSL Configuration
    SSLEngine on
    SSLCertificateFile {ssl_cert_path}
    SSLCertificateKeyFile {ssl_key_path}
    SSLProtocol all -SSLv3 -TLSv1 -TLSv1.1
    SSLCipherSuite ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384
    SSLHonorCipherOrder off

    # Logging
    ErrorLog  ${{APACHE_LOG_DIR}}/{service_name}-ssl-error.log
    CustomLog ${{APACHE_LOG_DIR}}/{service_name}-ssl-access.log combined

    # PHP-FPM
    <FilesMatch "\\.php$">
        SetHandler "proxy:unix:{fpm_socket}|fcgi://localhost"
    </FilesMatch>

    <Directory {document_root}>
        Options -Indexes +FollowSymLinks -MultiViews
        AllowOverride All
        Require all granted

        # Enable PATH_INFO for MVC frameworks
        AcceptPathInfo On

        <IfModule mod_rewrite.c>
            RewriteEngine On
            RewriteCond %{{REQUEST_FILENAME}} !-d
            RewriteCond %{{REQUEST_FILENAME}} !-f
            RewriteRule ^ index.php [L]
        </IfModule>
    </Directory>

    # Security Headers (with HSTS for SSL)
    <IfModule mod_headers.c>
        Header always set X-Frame-Options "SAMEORIGIN"
        Header always set X-Content-Type-Options "nosniff"
        Header always set X-XSS-Protection "1; mode=block"
        Header always set Referrer-Policy "strict-origin-when-cross-origin"
        Header always set Strict-Transport-Security "max-age=63072000; includeSubDomains; preload"
        Header always unset X-Powered-By
    </IfModule>

    # ── Deny Hidden Files ───────────────────────────────────
    <DirectoryMatch "/\\.">
        Require all denied
    </DirectoryMatch>

    # ── Deny Sensitive Files ────────────────────────────────
    <FilesMatch "^\\.(env|git|htaccess|htpasswd)">
        Require all denied
    </FilesMatch>

    <FilesMatch "(composer\\.json|composer\\.lock|package\\.json|package-lock\\.json)$">
        Require all denied
    </FilesMatch>

    # ── Deny PHP in Uploads ─────────────────────────────────
    <DirectoryMatch "/(?:uploads|files)/">
        <FilesMatch "\\.php$">
            Require all denied
        </FilesMatch>
    </DirectoryMatch>

    # ── Static Asset Caching ────────────────────────────────
    <IfModule mod_expires.c>
        ExpiresActive On
        ExpiresByType text/css "access plus 1 month"
        ExpiresByType application/javascript "access plus 1 month"
        ExpiresByType image/png "access plus 1 month"
        ExpiresByType image/jpeg "access plus 1 month"
        ExpiresByType image/gif "access plus 1 month"
        ExpiresByType image/svg+xml "access plus 1 month"
    </IfModule>

    <IfModule mod_deflate.c>
        AddOutputFilterByType DEFLATE text/plain text/css text/javascript text/xml application/json application/javascript application/xml image/svg+xml
    </IfModule>

    # ── Upload Size Limit ───────────────────────────────────
    LimitRequestBody {max_upload_bytes}

{extra_config}
</VirtualHost>
"""

    def __init__(self, system: SystemDetector, log: DeployLogger):
        self.system = system
        self.log = log
        self.os_info = system.detect_os()

    def _run(self, cmd: str) -> Tuple[int, str, str]:
        result = subprocess.run(
            cmd, shell=True, capture_output=True, text=True, timeout=60
        )
        return result.returncode, result.stdout.strip(), result.stderr.strip()

    def _enable_required_modules(self):
        """
        Enable required Apache modules for PHP-FPM proxy setup.
        Only applies to Debian/Ubuntu (a2enmod). On RHEL, modules
        are loaded via config files and typically available by default.
        """
        if self.os_info["family"] != "debian":
            return

        required_modules = [
            "proxy_fcgi",   # PHP-FPM proxy
            "rewrite",      # URL rewriting (Laravel, WP, etc.)
            "headers",      # Security headers
            "expires",      # Static asset caching
            "deflate",      # Gzip compression
            "ssl",          # SSL/TLS support
            "setenvif",     # ProxyFCGI env vars
        ]

        enabled = []
        for mod in required_modules:
            rc, _, _ = self._run(f"a2enmod {mod} 2>/dev/null")
            if rc == 0:
                enabled.append(mod)

        if enabled:
            self.log.info(f"Enabled Apache modules: {', '.join(enabled)}")

    # ── Paths ───────────────────────────────────────────────────

    def _get_paths(self) -> Dict:
        """Get correct Apache config paths for this distro."""
        if self.os_info["family"] == "debian":
            return {
                "sites_available": "/etc/apache2/sites-available",
                "sites_enabled": "/etc/apache2/sites-enabled",
                "use_symlink": True,
                "enable_cmd": "a2ensite",
                "disable_cmd": "a2dissite",
            }
        else:
            return {
                "conf_d": "/etc/httpd/conf.d",
                "use_symlink": False,
            }

    # ── Config Generation ───────────────────────────────────────

    def generate_vhost(self, config: Dict, backup: BackupManager) -> bool:
        """Generate Apache VirtualHost configuration."""
        service_name = config["service_name"]
        domain = config["domain"]
        enable_ssl = config.get("enable_ssl", False)

        self.log.step(f"Generating Apache vhost for [{service_name}]")

        paths = self._get_paths()

        if paths.get("use_symlink"):
            config_path = os.path.join(paths["sites_available"], f"{service_name}.conf")
        else:
            config_path = os.path.join(paths["conf_d"], f"{service_name}.conf")

        # Safety check
        if os.path.exists(config_path):
            with open(config_path, "r") as f:
                existing = f.read()
            if f"VirtualHost: {service_name}" in existing:
                self.log.info("Updating existing vhost config")
                backup.backup_file(config_path)
            else:
                self.log.error(
                    f"Vhost config exists but wasn't created by this agent: {config_path}"
                )
                self.log.error("Refusing to overwrite foreign config")
                return False

        # Ensure required Apache modules are enabled
        self._enable_required_modules()

        # Convert upload size to bytes for Apache LimitRequestBody
        max_upload = config.get("max_upload_size", "64M")
        max_bytes = self._parse_size_to_bytes(max_upload)

        # Conditional ServerAlias (skip for IP addresses)
        is_ip = bool(re.match(r'^(\d{1,3}\.){3}\d{1,3}$', domain))
        server_alias_line = "" if is_ip else f"    ServerAlias www.{domain}"

        tmpl_vars = {
            "service_name": service_name,
            "domain": domain,
            "server_alias_line": server_alias_line,
            "php_version": config["php_version"],
            "fpm_socket": config["fpm_socket"],
            "document_root": config["document_root"],
            "max_upload_bytes": max_bytes,
            "extra_config": config.get("extra_apache_config", ""),
        }

        if enable_ssl:
            ssl_cert = config.get("ssl_cert_path", f"/etc/letsencrypt/live/{domain}/fullchain.pem")
            ssl_key = config.get("ssl_key_path", f"/etc/letsencrypt/live/{domain}/privkey.pem")
            tmpl_vars["ssl_cert_path"] = ssl_cert
            tmpl_vars["ssl_key_path"] = ssl_key
            content = self.VHOST_SSL_REDIRECT.format(**tmpl_vars)
            content += "\n"
            content += self.VHOST_SSL_TEMPLATE.format(**tmpl_vars)
        else:
            content = self.VHOST_HTTP_TEMPLATE.format(**tmpl_vars)

        # Write config
        try:
            os.makedirs(os.path.dirname(config_path), exist_ok=True)
            with open(config_path, "w") as f:
                f.write(content)
            os.chmod(config_path, 0o644)
            self.log.success(f"Vhost written: {config_path}")
        except Exception as e:
            self.log.error(f"Failed to write vhost: {e}")
            return False

        # Enable site
        if paths.get("use_symlink"):
            rc, _, err = self._run(f"a2ensite {service_name}.conf")
            if rc != 0:
                self.log.warn(f"a2ensite warning: {err}")
            self.log.info(f"Site enabled via a2ensite")

        return True

    # ── Config Validation & Reload ──────────────────────────────

    def test_config(self) -> bool:
        """Test Apache configuration syntax."""
        self.log.info("Testing Apache configuration...")
        success, output = self.system.apache_config_test()
        if success:
            self.log.success("Apache configuration test passed")
        else:
            self.log.error(f"Apache configuration test FAILED:\n{output}")
        return success

    def safe_reload(self) -> bool:
        """Safely reload Apache."""
        self.log.step("Safely reloading Apache")

        if not self.test_config():
            self.log.error("Aborting reload - configuration invalid")
            return False

        apache_cmd = self.system.get_apache_command()

        if self.system.is_apache_running():
            rc, _, err = self._run(f"systemctl reload {apache_cmd}")
            if rc != 0:
                self.log.error(f"Apache reload failed: {err}")
                return False
        else:
            rc, _, err = self._run(f"systemctl start {apache_cmd}")
            if rc != 0:
                self.log.error(f"Apache start failed: {err}")
                return False

        if not self.system.is_apache_running():
            self.log.error("Apache is not running after reload")
            return False

        self.log.success("Apache reloaded successfully")
        return True

    # ── Removal (for rollback) ──────────────────────────────────

    def remove_vhost(self, service_name: str) -> bool:
        """Remove a vhost configuration."""
        paths = self._get_paths()

        if paths.get("use_symlink"):
            self._run(f"a2dissite {service_name}.conf 2>/dev/null")
            for p in [
                os.path.join(paths["sites_available"], f"{service_name}.conf"),
                os.path.join(paths["sites_enabled"], f"{service_name}.conf"),
            ]:
                if os.path.exists(p) or os.path.islink(p):
                    os.unlink(p)
                    self.log.info(f"Removed: {p}")
        else:
            p = os.path.join(paths["conf_d"], f"{service_name}.conf")
            if os.path.exists(p):
                os.unlink(p)
                self.log.info(f"Removed: {p}")
        return True

    # ── Helpers ──────────────────────────────────────────────────

    @staticmethod
    def _parse_size_to_bytes(size_str: str) -> int:
        """Convert '64M' style sizes to bytes."""
        size_str = size_str.strip().upper()
        multipliers = {"K": 1024, "M": 1024**2, "G": 1024**3}
        for suffix, mult in multipliers.items():
            if size_str.endswith(suffix):
                return int(size_str[:-1]) * mult
        return int(size_str)
