"""
Nginx Configuration Generator - Universal Deployment Agent
=============================================================
Generates production-grade Nginx vhost configs with
security headers, gzip, PHP-FPM integration, and
reverse proxy support for all languages.
"""

import os
import re
import subprocess
from typing import Dict, Optional, Tuple

from modules.logger import DeployLogger
from modules.system import SystemDetector
from modules.backup import BackupManager


class NginxConfigurator:
    """
    Generates and manages Nginx server block configurations:
    - Per-service vhost files
    - PHP-FPM socket integration (PHP)
    - Reverse proxy to app port (Python, Node, Ruby, Go, Java, Rust, .NET)
    - Static file serving (static sites)
    - Security headers
    - Gzip compression
    - Rate limiting
    - Hidden file protection
    - SSL/TLS support
    - Safe config testing before reload
    """

    # ── Nginx HTTP vhost template ───────────────────────────────
    VHOST_HTTP_TEMPLATE = """# ============================================================
# Nginx Server Block: {service_name}
# Domain:  {domain}
# PHP:     {php_version} via FPM
# Socket:  {fpm_socket}
# Generated by PHP-FPM Automation Agent
# ============================================================

server {{
    listen 80;
    listen [::]:80;
    server_name {server_name};

    root {document_root};
    index index.php index.html index.htm;

    # Access & Error Logs
    access_log /var/log/nginx/{service_name}-access.log combined buffer=512k flush=1m;
    error_log  /var/log/nginx/{service_name}-error.log warn;

    # ── Security Headers ────────────────────────────────────
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    # ── Client Settings ─────────────────────────────────────
    client_max_body_size {max_upload_size};
    client_body_timeout 60s;
    client_header_timeout 60s;
    send_timeout 60s;
    keepalive_timeout 65s;

    # ── Gzip Compression ────────────────────────────────────
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 4;
    gzip_min_length 256;
    gzip_types
        text/plain
        text/css
        text/javascript
        text/xml
        application/json
        application/javascript
        application/xml
        application/xml+rss
        application/vnd.ms-fontobject
        font/opentype
        image/svg+xml;

    # ── Security: Deny Hidden Files (BEFORE PHP location) ──
    location ~ /\\. {{
        deny all;
        access_log off;
        log_not_found off;
    }}

    # ── Deny access to PHP files in uploads ─────────────────
    location ~* /(?:uploads|files)/.*\\.php$ {{
        deny all;
    }}

    # ── Main Location ───────────────────────────────────────
    location / {{
        try_files $uri $uri/ /index.php?$query_string;
    }}

    # ── PHP Processing (supports PATH_INFO for MVC routers) ─
    location ~ \\.php(/|$) {{
        # Mitigate https://httpoxy.org/ vulnerabilities
        fastcgi_param HTTP_PROXY "";

        # Split script name and path info
        fastcgi_split_path_info ^(.+?\\.php)(/.*)$;

        # Ensure the PHP script exists before passing to FPM
        try_files $fastcgi_script_name =404;

        fastcgi_pass unix:{fpm_socket};
        fastcgi_index index.php;

        # FastCGI parameters
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param DOCUMENT_ROOT $document_root;

        # FastCGI tuning
        fastcgi_connect_timeout 60s;
        fastcgi_send_timeout 300s;
        fastcgi_read_timeout 300s;
        fastcgi_buffer_size 128k;
        fastcgi_buffers 4 256k;
        fastcgi_busy_buffers_size 256k;
        fastcgi_temp_file_write_size 256k;

        # Security: Don't log favicon/robots
        fastcgi_intercept_errors on;
    }}

    # ── Static Assets ───────────────────────────────────────
    location ~* \\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot|webp|avif)$ {{
        expires 30d;
        add_header Cache-Control "public, immutable";
        access_log off;
        log_not_found off;
        try_files $uri =404;
    }}

    # ── Security: Deny Sensitive Files ──────────────────────
    location ~* (?:composer\\.json|composer\\.lock|package\\.json|package-lock\\.json|\\.env|\\.git|readme|changelog|license)$ {{
        deny all;
        access_log off;
        log_not_found off;
    }}

    # ── Robots.txt ──────────────────────────────────────────
    location = /robots.txt {{
        access_log off;
        log_not_found off;
    }}

    # ── Favicon ─────────────────────────────────────────────
    location = /favicon.ico {{
        access_log off;
        log_not_found off;
    }}

{extra_config}
}}
"""

    # ── Nginx HTTPS redirect + SSL vhost ────────────────────────
    VHOST_SSL_REDIRECT = """# HTTP → HTTPS redirect for {domain}
server {{
    listen 80;
    listen [::]:80;
    server_name {server_name};
    return 301 https://$server_name$request_uri;
}}
"""

    VHOST_SSL_TEMPLATE = """# ============================================================
# Nginx SSL Server Block: {service_name}
# Domain:  {domain}
# PHP:     {php_version} via FPM
# Socket:  {fpm_socket}
# Generated by PHP-FPM Automation Agent
# ============================================================

server {{
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name {server_name};

    # SSL Certificate
    ssl_certificate {ssl_cert_path};
    ssl_certificate_key {ssl_key_path};

    # Modern SSL configuration
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:10m;
    ssl_session_tickets off;

    # OCSP Stapling
    ssl_stapling on;
    ssl_stapling_verify on;

    root {document_root};
    index index.php index.html index.htm;

    access_log /var/log/nginx/{service_name}-ssl-access.log combined buffer=512k flush=1m;
    error_log  /var/log/nginx/{service_name}-ssl-error.log warn;

    # Security Headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always;
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;

    client_max_body_size {max_upload_size};

    # Gzip
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 4;
    gzip_min_length 256;
    gzip_types text/plain text/css text/javascript text/xml application/json application/javascript application/xml application/xml+rss application/vnd.ms-fontobject font/opentype image/svg+xml;

    # Security: Deny Hidden Files (BEFORE PHP location)
    location ~ /\\. {{ deny all; access_log off; log_not_found off; }}

    # Deny access to PHP files in uploads
    location ~* /(?:uploads|files)/.*\\.php$ {{ deny all; }}

    location / {{
        try_files $uri $uri/ /index.php?$query_string;
    }}

    location ~ \\.php(/|$) {{
        fastcgi_param HTTP_PROXY "";
        fastcgi_split_path_info ^(.+?\\.php)(/.*)$;
        try_files $fastcgi_script_name =404;
        fastcgi_pass unix:{fpm_socket};
        fastcgi_index index.php;

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param DOCUMENT_ROOT $document_root;
        fastcgi_connect_timeout 60s;
        fastcgi_send_timeout 300s;
        fastcgi_read_timeout 300s;
        fastcgi_buffer_size 128k;
        fastcgi_buffers 4 256k;
        fastcgi_busy_buffers_size 256k;
    }}

    location ~* \\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot|webp|avif)$ {{
        expires 30d;
        add_header Cache-Control "public, immutable";
        access_log off;
        log_not_found off;
        try_files $uri =404;
    }}

    location ~* (?:composer\\.json|composer\\.lock|package\\.json|\\.env|\\.git|readme|changelog|license)$ {{ deny all; }}

{extra_config}
}}
"""

    # ── Reverse Proxy HTTP template (Node, Python, Ruby, Go, Java, Rust, .NET) ──
    REVERSE_PROXY_HTTP_TEMPLATE = """# ============================================================
# Nginx Server Block: {service_name}
# Domain:   {domain}
# Language: {language}
# Upstream:  127.0.0.1:{app_port}
# Generated by Universal Deployment Agent
# ============================================================

upstream {upstream_name} {{
    server 127.0.0.1:{app_port};
    keepalive 64;
}}

server {{
    listen 80;
    listen [::]:80;
    server_name {server_name};

    root {document_root};

    # Access & Error Logs
    access_log /var/log/nginx/{service_name}-access.log combined buffer=512k flush=1m;
    error_log  /var/log/nginx/{service_name}-error.log warn;

    # ── Security Headers ────────────────────────────────────
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always;

    # ── Client Settings ─────────────────────────────────────
    client_max_body_size {max_upload_size};
    client_body_timeout 60s;
    client_header_timeout 60s;
    send_timeout 60s;
    keepalive_timeout 65s;

    # ── Gzip Compression ────────────────────────────────────
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 4;
    gzip_min_length 256;
    gzip_types
        text/plain text/css text/javascript text/xml
        application/json application/javascript application/xml
        application/xml+rss image/svg+xml;

    # ── Security: Deny Hidden Files ─────────────────────────
    location ~ /\\. {{
        deny all;
        access_log off;
        log_not_found off;
    }}

    # ── Static Assets (served directly by Nginx) ────────────
    location ~* \\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot|webp|avif)$ {{
        expires 30d;
        add_header Cache-Control "public, immutable";
        access_log off;
        log_not_found off;
        try_files $uri @backend;
    }}

    # ── Deny Sensitive Files ────────────────────────────────
    location ~* (?:\\.env|\\.git|readme|changelog|license)$ {{
        deny all;
        access_log off;
    }}

    # ── Reverse Proxy to Application ────────────────────────
    location / {{
        proxy_pass http://{upstream_name};
        proxy_http_version 1.1;

        # WebSocket support
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # Forward real client info
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;

        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 300s;
        proxy_read_timeout 300s;

        # Buffering
        proxy_buffering on;
        proxy_buffer_size 128k;
        proxy_buffers 4 256k;
        proxy_busy_buffers_size 256k;
    }}

    # ── Named backend location ──────────────────────────────
    location @backend {{
        proxy_pass http://{upstream_name};
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }}

{extra_config}
}}
"""

    # ── Reverse Proxy SSL template ──────────────────────────────
    REVERSE_PROXY_SSL_TEMPLATE = """# ============================================================
# Nginx SSL Server Block: {service_name}
# Domain:   {domain}
# Language: {language}
# Upstream:  127.0.0.1:{app_port}
# Generated by Universal Deployment Agent
# ============================================================

upstream {upstream_name} {{
    server 127.0.0.1:{app_port};
    keepalive 64;
}}

server {{
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name {server_name};

    # SSL Certificate
    ssl_certificate {ssl_cert_path};
    ssl_certificate_key {ssl_key_path};
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:10m;
    ssl_session_tickets off;
    ssl_stapling on;
    ssl_stapling_verify on;

    root {document_root};

    access_log /var/log/nginx/{service_name}-ssl-access.log combined buffer=512k flush=1m;
    error_log  /var/log/nginx/{service_name}-ssl-error.log warn;

    # Security Headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;

    client_max_body_size {max_upload_size};

    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 4;
    gzip_min_length 256;
    gzip_types text/plain text/css text/javascript text/xml application/json application/javascript application/xml image/svg+xml;

    location ~ /\\. {{ deny all; access_log off; log_not_found off; }}

    location ~* \\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot|webp|avif)$ {{
        expires 30d;
        add_header Cache-Control "public, immutable";
        access_log off;
        try_files $uri @backend;
    }}

    location ~* (?:\\.env|\\.git|readme|changelog|license)$ {{ deny all; }}

    location / {{
        proxy_pass http://{upstream_name};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_connect_timeout 60s;
        proxy_send_timeout 300s;
        proxy_read_timeout 300s;
        proxy_buffering on;
        proxy_buffer_size 128k;
        proxy_buffers 4 256k;
    }}

    location @backend {{
        proxy_pass http://{upstream_name};
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }}

{extra_config}
}}
"""

    # ── Static Site HTTP template ───────────────────────────────
    STATIC_HTTP_TEMPLATE = """# ============================================================
# Nginx Server Block: {service_name}
# Domain:   {domain}
# Type:     Static Site
# Generated by Universal Deployment Agent
# ============================================================

server {{
    listen 80;
    listen [::]:80;
    server_name {server_name};

    root {document_root};
    index index.html index.htm;

    access_log /var/log/nginx/{service_name}-access.log combined buffer=512k flush=1m;
    error_log  /var/log/nginx/{service_name}-error.log warn;

    # Security Headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    # Gzip
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_min_length 256;
    gzip_types text/plain text/css text/javascript text/xml application/json application/javascript application/xml image/svg+xml;

    # SPA routing — try files then fall back to index.html
    location / {{
        try_files $uri $uri/ /index.html;
    }}

    # Static Assets
    location ~* \\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot|webp|avif|map)$ {{
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
    }}

    # Security
    location ~ /\\. {{ deny all; access_log off; log_not_found off; }}
    location ~* (?:\\.env|\\.git)$ {{ deny all; }}

{extra_config}
}}
"""

    def __init__(self, system: SystemDetector, log: DeployLogger):
        self.system = system
        self.log = log

    def _run(self, cmd: str) -> Tuple[int, str, str]:
        result = subprocess.run(
            cmd, shell=True, capture_output=True, text=True, timeout=60
        )
        return result.returncode, result.stdout.strip(), result.stderr.strip()

    # ── Config Generation ───────────────────────────────────────

    def generate_vhost(self, config: Dict, backup: BackupManager) -> bool:
        """
        Generate Nginx server block configuration.
        Handles PHP-FPM, reverse proxy, and static site configurations.
        """
        service_name = config["service_name"]
        domain = config["domain"]
        enable_ssl = config.get("enable_ssl", False)
        language = config.get("language", "php")

        self.log.step(f"Generating Nginx vhost for [{service_name}] ({language})")

        # Determine config paths
        sites_available = "/etc/nginx/sites-available"
        sites_enabled = "/etc/nginx/sites-enabled"
        conf_d = "/etc/nginx/conf.d"

        # Use sites-available/sites-enabled if they exist (Debian/Ubuntu)
        if os.path.isdir(sites_available):
            config_path = os.path.join(sites_available, f"{service_name}.conf")
            symlink_path = os.path.join(sites_enabled, f"{service_name}.conf")
            use_symlink = True
        else:
            os.makedirs(conf_d, exist_ok=True)
            config_path = os.path.join(conf_d, f"{service_name}.conf")
            symlink_path = None
            use_symlink = False

        # Check for existing config (safety: never overwrite other services)
        if os.path.exists(config_path):
            with open(config_path, "r") as f:
                existing = f.read()
            if f"Server Block: {service_name}" in existing or f"VirtualHost: {service_name}" in existing:
                self.log.info("Updating existing vhost config")
                backup.backup_file(config_path)
            else:
                self.log.error(
                    f"Vhost config exists but wasn't created by this agent: {config_path}"
                )
                self.log.error("Refusing to overwrite foreign config")
                return False

        # Build template variables
        is_ip = bool(re.match(r'^(\d{1,3}\.){3}\d{1,3}$', domain))
        server_name = domain if is_ip else f"{domain} www.{domain}"

        # Determine which template to use based on language
        if language == "php":
            content = self._generate_php_vhost(config, server_name, enable_ssl)
        elif language == "static":
            content = self._generate_static_vhost(config, server_name, enable_ssl)
        else:
            # Reverse proxy for all other languages
            content = self._generate_proxy_vhost(config, server_name, enable_ssl)

        # Write config
        try:
            with open(config_path, "w") as f:
                f.write(content)
            os.chmod(config_path, 0o644)
            self.log.success(f"Vhost written: {config_path}")
        except Exception as e:
            self.log.error(f"Failed to write vhost: {e}")
            return False

        # Enable site (create symlink)
        if use_symlink and symlink_path:
            if os.path.islink(symlink_path):
                os.unlink(symlink_path)
            elif os.path.exists(symlink_path):
                backup.backup_file(symlink_path)
                os.unlink(symlink_path)

            os.symlink(config_path, symlink_path)
            self.log.info(f"Site enabled: {symlink_path}")

        return True

    # ── Template Builders ───────────────────────────────────────

    def _generate_php_vhost(self, config: Dict, server_name: str, enable_ssl: bool) -> str:
        """Generate PHP-FPM vhost (original behavior)."""
        domain = config["domain"]
        tmpl_vars = {
            "service_name": config["service_name"],
            "domain": domain,
            "server_name": server_name,
            "php_version": config.get("php_version", config.get("runtime_version", "8.2")),
            "fpm_socket": config.get("fpm_socket", ""),
            "document_root": config["document_root"],
            "max_upload_size": config.get("max_upload_size", "64M"),
            "extra_config": config.get("extra_nginx_config", ""),
        }
        if enable_ssl:
            ssl_cert = config.get("ssl_cert_path", f"/etc/letsencrypt/live/{domain}/fullchain.pem")
            ssl_key = config.get("ssl_key_path", f"/etc/letsencrypt/live/{domain}/privkey.pem")
            tmpl_vars["ssl_cert_path"] = ssl_cert
            tmpl_vars["ssl_key_path"] = ssl_key
            content = self.VHOST_SSL_REDIRECT.format(**tmpl_vars)
            content += "\n"
            content += self.VHOST_SSL_TEMPLATE.format(**tmpl_vars)
        else:
            content = self.VHOST_HTTP_TEMPLATE.format(**tmpl_vars)
        return content

    def _generate_proxy_vhost(self, config: Dict, server_name: str, enable_ssl: bool) -> str:
        """Generate reverse proxy vhost for non-PHP languages."""
        domain = config["domain"]
        service_name = config["service_name"]
        # Create a safe upstream name (no dots or special chars)
        upstream_name = re.sub(r'[^a-zA-Z0-9]', '_', service_name) + "_upstream"

        tmpl_vars = {
            "service_name": service_name,
            "domain": domain,
            "server_name": server_name,
            "language": config.get("language", "app"),
            "app_port": config.get("app_port", 3000),
            "upstream_name": upstream_name,
            "document_root": config.get("document_root", config.get("deploy_path", "")),
            "max_upload_size": config.get("max_upload_size", "64M"),
            "extra_config": config.get("extra_nginx_config", ""),
        }
        if enable_ssl:
            ssl_cert = config.get("ssl_cert_path", f"/etc/letsencrypt/live/{domain}/fullchain.pem")
            ssl_key = config.get("ssl_key_path", f"/etc/letsencrypt/live/{domain}/privkey.pem")
            tmpl_vars["ssl_cert_path"] = ssl_cert
            tmpl_vars["ssl_key_path"] = ssl_key
            content = self.VHOST_SSL_REDIRECT.format(**tmpl_vars)
            content += "\n"
            content += self.REVERSE_PROXY_SSL_TEMPLATE.format(**tmpl_vars)
        else:
            content = self.REVERSE_PROXY_HTTP_TEMPLATE.format(**tmpl_vars)
        return content

    def _generate_static_vhost(self, config: Dict, server_name: str, enable_ssl: bool) -> str:
        """Generate static site vhost (no backend process)."""
        tmpl_vars = {
            "service_name": config["service_name"],
            "domain": config["domain"],
            "server_name": server_name,
            "document_root": config.get("document_root", config.get("deploy_path", "")),
            "extra_config": config.get("extra_nginx_config", ""),
        }
        # For static sites, use the static template (HTTP only shown; SSL can be added)
        content = self.STATIC_HTTP_TEMPLATE.format(**tmpl_vars)
        return content

    # ── Config Validation & Reload ──────────────────────────────

    def test_config(self) -> bool:
        """Test Nginx configuration syntax."""
        self.log.info("Testing Nginx configuration...")
        success, output = self.system.nginx_config_test()
        if success:
            self.log.success("Nginx configuration test passed")
        else:
            self.log.error(f"Nginx configuration test FAILED:\n{output}")
        return success

    def safe_reload(self) -> bool:
        """
        Safely reload Nginx:
        1. Test config
        2. Reload (not restart)
        3. Verify running
        """
        self.log.step("Safely reloading Nginx")

        # Test first
        if not self.test_config():
            self.log.error("Aborting reload - configuration invalid")
            return False

        # Reload
        if self.system.is_nginx_running():
            rc, _, err = self._run("systemctl reload nginx")
            if rc != 0:
                self.log.error(f"Nginx reload failed: {err}")
                return False
        else:
            rc, _, err = self._run("systemctl start nginx")
            if rc != 0:
                self.log.error(f"Nginx start failed: {err}")
                return False

        # Verify
        if not self.system.is_nginx_running():
            self.log.error("Nginx is not running after reload")
            return False

        self.log.success("Nginx reloaded successfully")
        return True

    # ── Removal (for rollback) ──────────────────────────────────

    def remove_vhost(self, service_name: str) -> bool:
        """Remove a vhost configuration (for rollback)."""
        for path in [
            f"/etc/nginx/sites-enabled/{service_name}.conf",
            f"/etc/nginx/sites-available/{service_name}.conf",
            f"/etc/nginx/conf.d/{service_name}.conf",
        ]:
            if os.path.exists(path) or os.path.islink(path):
                os.unlink(path)
                self.log.info(f"Removed: {path}")
        return True
