"""
PHP-FPM Pool Manager - PHP-FPM Automation Agent
=================================================
Creates and manages isolated PHP-FPM pools per service.
Each service gets its own pool, socket, user, and resource limits.
"""

import os
import subprocess
from typing import Dict, Optional, Tuple

from modules.logger import DeployLogger
from modules.system import SystemDetector
from modules.backup import BackupManager


class PHPFPMManager:
    """
    Manages PHP-FPM pool configurations:
    - Creates per-service pool configs
    - Unique unix socket per pool
    - Dedicated system user per pool
    - Resource limits and isolation
    - Safe reload (never restart blindly)
    """

    POOL_TEMPLATE = """[{pool_name}]
; ============================================================
; PHP-FPM Pool: {pool_name}
; Service: {service_name}
; Domain:  {domain}
; Generated by PHP-FPM Automation Agent
; ============================================================

; Process user/group
user = {user}
group = {group}

; Listen on unix socket (faster than TCP, more secure)
listen = {socket_path}
listen.owner = {user}
listen.group = {group}
listen.mode = 0660

; Process manager: dynamic for production
pm = dynamic
pm.max_children = {max_children}
pm.start_servers = {start_servers}
pm.min_spare_servers = {min_spare}
pm.max_spare_servers = {max_spare}
pm.max_requests = {max_requests}
pm.process_idle_timeout = 10s

; Status page (restrict to localhost)
pm.status_path = /fpm-status-{pool_name}
ping.path = /fpm-ping-{pool_name}
ping.response = pong

; Logging
access.log = /var/log/php-fpm/{pool_name}-access.log
access.format = "%R - %u %t \\"%m %r%Q%q\\" %s %f %{{mili}}d %{{kilo}}M %C%%"
slowlog = /var/log/php-fpm/{pool_name}-slow.log
request_slowlog_timeout = 5s
catch_workers_output = yes
decorate_workers_output = no

; Timeouts
request_terminate_timeout = {max_execution_time}s

; Security: restrict to deploy path
chdir = {deploy_path}
; Uncomment for strict isolation (breaks some apps):
; chroot = {deploy_path}

; Security: clear environment and set specific vars
clear_env = yes

; Environment variables
env[HOSTNAME] = $HOSTNAME
env[PATH] = /usr/local/bin:/usr/bin:/bin
env[TMP] = /tmp
env[TMPDIR] = /tmp
env[TEMP] = /tmp

; PHP settings overrides
php_admin_value[error_log] = /var/log/php-fpm/{pool_name}-error.log
php_admin_flag[log_errors] = on
php_admin_value[memory_limit] = {memory_limit}
php_admin_value[max_execution_time] = {max_execution_time}
php_admin_value[max_input_time] = 60
php_admin_value[upload_max_filesize] = {max_upload_size}
php_admin_value[post_max_size] = {max_upload_size}
php_admin_value[max_input_vars] = 3000

; Security hardening
php_admin_value[open_basedir] = {deploy_path}:/tmp:/usr/share/php
php_admin_value[disable_functions] = exec,passthru,shell_exec,system,proc_open,popen,parse_ini_file,show_source
php_admin_flag[expose_php] = off
php_admin_value[session.cookie_httponly] = 1
php_admin_value[session.cookie_secure] = {cookie_secure}
php_admin_value[session.use_strict_mode] = 1

; OPcache per-pool settings
php_admin_value[opcache.enable] = 1
php_admin_value[opcache.memory_consumption] = 128
php_admin_value[opcache.interned_strings_buffer] = 16
php_admin_value[opcache.max_accelerated_files] = 10000
php_admin_value[opcache.validate_timestamps] = 1
php_admin_value[opcache.revalidate_freq] = 2
"""

    def __init__(self, system: SystemDetector, log: DeployLogger):
        self.system = system
        self.log = log

    def _run(self, cmd: str) -> Tuple[int, str, str]:
        result = subprocess.run(
            cmd, shell=True, capture_output=True, text=True, timeout=60
        )
        return result.returncode, result.stdout.strip(), result.stderr.strip()

    # ── Pool Configuration ──────────────────────────────────────

    def create_pool(self, config: Dict, backup: BackupManager) -> bool:
        """
        Create a PHP-FPM pool configuration for a service.
        Backs up existing config before writing.
        """
        service_name = config["service_name"]
        php_version = config["php_version"]
        pool_config_path = config["fpm_pool_config"]

        self.log.step(f"Configuring PHP-FPM pool for [{service_name}]")

        # Ensure log directory exists
        os.makedirs("/var/log/php-fpm", exist_ok=True)

        # Ensure run directory exists
        os.makedirs("/run/php", exist_ok=True)

        # Backup existing pool config if it exists
        if os.path.exists(pool_config_path):
            backup.backup_file(pool_config_path)
            self.log.info(f"Backed up existing pool config: {pool_config_path}")

        # Generate pool config
        pool_content = self.POOL_TEMPLATE.format(
            pool_name=service_name,
            service_name=service_name,
            domain=config["domain"],
            user=config["user"],
            group=config.get("group", "www-data"),
            socket_path=config["fpm_socket"],
            deploy_path=config["deploy_path"],
            max_children=config.get("php_pool_max_children", 10),
            start_servers=config.get("php_pool_start_servers", 2),
            min_spare=config.get("php_pool_min_spare", 1),
            max_spare=config.get("php_pool_max_spare", 4),
            max_requests=config.get("php_pool_max_requests", 500),
            memory_limit=config.get("php_memory_limit", "256M"),
            max_execution_time=config.get("php_max_execution_time", 300),
            max_upload_size=config.get("max_upload_size", "64M"),
            cookie_secure="1" if config.get("enable_ssl") else "0",
        )

        # Add environment file variables if specified
        env_file = config.get("environment_file")
        if env_file and os.path.exists(env_file):
            pool_content += "\n; Custom environment from environment_file\n"
            try:
                with open(env_file, "r") as f:
                    for line in f:
                        line = line.strip()
                        if line and not line.startswith("#") and "=" in line:
                            key, value = line.split("=", 1)
                            key = key.strip()
                            value = value.strip().strip('"').strip("'")
                            pool_content += f'env[{key}] = "{value}"\n'
            except Exception as e:
                self.log.warn(f"Could not parse environment file: {e}")

        # Inject database environment variables from auto-detected credentials
        db_creds = config.get("_db_credentials", {})
        if db_creds and db_creds.get("dbname"):
            pool_content += "\n; Database environment variables (auto-detected)\n"
            env_map = {
                "DB_HOST": db_creds.get("host", "localhost"),
                "DB_PORT": db_creds.get("port", ""),
                "DB_NAME": db_creds.get("dbname", ""),
                "DB_DATABASE": db_creds.get("dbname", ""),
                "DB_USER": db_creds.get("user", ""),
                "DB_USERNAME": db_creds.get("user", ""),
                "DB_PASS": db_creds.get("password", ""),
                "DB_PASSWORD": db_creds.get("password", ""),
            }
            # Also set driver-specific env vars
            db_driver = config.get("_db_driver", "")
            if db_driver:
                env_map["DB_CONNECTION"] = db_driver
            for key, value in env_map.items():
                if value:
                    pool_content += f'env[{key}] = "{value}"\n'
            self.log.info("Injected database env vars into FPM pool")

        # Write pool config
        pool_dir = os.path.dirname(pool_config_path)
        os.makedirs(pool_dir, exist_ok=True)

        try:
            with open(pool_config_path, "w") as f:
                f.write(pool_content)
            os.chmod(pool_config_path, 0o644)
            self.log.success(f"Pool config written: {pool_config_path}")
        except Exception as e:
            self.log.error(f"Failed to write pool config: {e}")
            return False

        return True

    # ── System User Management ──────────────────────────────────

    def ensure_service_user(self, config: Dict) -> bool:
        """Create dedicated system user for the service if it doesn't exist."""
        user = config["user"]
        group = config.get("group", "www-data")

        self.log.step(f"Ensuring service user: {user}")

        # Check if user already exists
        if self.system.user_exists(user):
            self.log.skip(f"User '{user}' already exists")
            return True

        # Ensure group exists
        if not self.system.group_exists(group):
            self.log.info(f"Creating group: {group}")
            rc, _, err = self._run(f"groupadd --system {group}")
            if rc != 0 and "already exists" not in err:
                self.log.error(f"Failed to create group {group}: {err}")
                return False

        # Create system user (no login, no home directory creation)
        self.log.info(f"Creating system user: {user}")
        rc, _, err = self._run(
            f"useradd --system --no-create-home --shell /usr/sbin/nologin "
            f"--gid {group} {user}"
        )
        if rc != 0 and "already exists" not in err:
            self.log.error(f"Failed to create user {user}: {err}")
            return False

        # Add user to www-data group for web server socket access
        self._run(f"usermod -aG www-data {user} 2>/dev/null")

        self.log.success(f"Service user '{user}' ready")
        return True

    # ── Pool Validation ─────────────────────────────────────────

    def validate_pool(self, config: Dict) -> bool:
        """Validate the PHP-FPM pool configuration."""
        php_version = config["php_version"]
        fpm_service = self.system.get_php_fpm_service_name(php_version)

        self.log.info(f"Validating PHP-FPM configuration for PHP {php_version}")

        # Test PHP-FPM config
        rc, out, err = self._run(f"php-fpm{php_version} -t 2>&1")
        output = out or err

        if rc != 0 and "error" in output.lower():
            self.log.error(f"PHP-FPM config test failed: {output}")
            return False

        self.log.success("PHP-FPM configuration valid")
        return True

    # ── Service Management ──────────────────────────────────────

    def reload_fpm(self, config: Dict) -> bool:
        """
        Safely reload PHP-FPM:
        1. Validate config first
        2. Use reload (not restart) to avoid downtime
        3. Verify service is running after reload
        """
        php_version = config["php_version"]
        fpm_service = self.system.get_php_fpm_service_name(php_version)

        self.log.step(f"Reloading PHP-FPM {php_version}")

        # Step 1: Validate config
        if not self.validate_pool(config):
            self.log.error("Aborting reload - configuration invalid")
            return False

        # Step 2: Check if service is running
        is_running = self.system.is_php_fpm_running(php_version)

        if is_running:
            # Reload (graceful, no downtime)
            rc, _, err = self._run(f"systemctl reload {fpm_service}")
            if rc != 0:
                self.log.warn(f"Reload failed, trying restart: {err}")
                rc, _, err = self._run(f"systemctl restart {fpm_service}")
                if rc != 0:
                    self.log.error(f"Failed to restart {fpm_service}: {err}")
                    return False
        else:
            # Start service
            rc, _, err = self._run(f"systemctl start {fpm_service}")
            if rc != 0:
                self.log.error(f"Failed to start {fpm_service}: {err}")
                return False

        # Step 3: Verify running
        rc, _, _ = self._run(f"systemctl is-active {fpm_service}")
        if rc != 0:
            self.log.error(f"{fpm_service} is not running after reload")
            return False

        self.log.success(f"PHP-FPM {php_version} reloaded successfully")
        return True

    # ── Pool Removal (for rollback) ─────────────────────────────

    def remove_pool(self, config: Dict) -> bool:
        """Remove a pool config (for rollback purposes)."""
        pool_config_path = config["fpm_pool_config"]
        if os.path.exists(pool_config_path):
            os.remove(pool_config_path)
            self.log.info(f"Removed pool config: {pool_config_path}")
        return True

    # ── Pool Status ─────────────────────────────────────────────

    def get_pool_status(self, config: Dict) -> Dict:
        """Get status information about a pool."""
        service_name = config["service_name"]
        php_version = config["php_version"]
        socket_path = config["fpm_socket"]
        pool_config = config["fpm_pool_config"]

        return {
            "pool_name": service_name,
            "php_version": php_version,
            "config_exists": os.path.exists(pool_config),
            "socket_exists": os.path.exists(socket_path),
            "fpm_running": self.system.is_php_fpm_running(php_version),
        }
